feat(actions): add place bid action
metaplex/js pull request #52
Opened 2021-11-04 19:44 UTC by kurpav

- added action to place bid
- tested place bid transaction instructions in metaplex-foundation repo

2021-11-04 21:39 UTC, b2kdaman requested changes

2021-11-04 21:39 UTC, b2kdaman commented on src/actions/placeBid.ts
> +      bidder,
Is this OK?

2021-11-05 07:29 UTC, m-sebastiyan approved these changes

2021-11-05 09:09 UTC, kurpav commented on src/actions/placeBid.ts
> +      bidder,
Do you mean two params `bidder` ?

2021-11-05 09:11 UTC, b2kdaman commented on src/actions/placeBid.ts
> +      bidder,
Yes

2021-11-05 09:26 UTC, kurpav commented on src/actions/placeBid.ts
> +      bidder,
Yes, the params passed correctly

2021-11-05 09:29 UTC, b2kdaman approved these changes

2021-11-05 09:29 UTC, merged

2021-11-05 09:31 UTC, m-sebastiyan commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@metaplex/js/v/3.3.0)
- [GitHub release](https://github.com/metaplex/js/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: